version: 2

sources:
  - name: pandemic_insight
    database: raw
    schema: pandemic_insight
    tables:
      - name: testscorebystate
        description: "Test scores of students by state and grade"
        columns:
          - name: year
            tests:
              - not_null
          - name: state
            tests:
              - not_null
          - name: subject
            tests:
              - not_null
          - name: grade
            tests:
              - not_null

      - name: covidbystate
        description: "COVID statistics by state"
        columns:
          - name: year
            tests:
              - not_null
          - name: state
            tests:
              - not_null

      - name: remotelearningbystate
        description: "The type of remote learning by state"
        columns:
          - name: subject
            tests:
              - not_null
          - name: grade
            tests:
              - not_null
          - name: year
            tests:
              - not_null
          - name: state
            tests:
              - not_null
